# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).
{
  config,
  pkgs,
  inputs,
  lib,
  ...
}: {
  imports = [
    ./hardware-configuration.nix
    # inputs.nixvim.nixosModules.nixvim
    inputs.ucodenix.nixosModules.default
    # inputs.nix-minecraft.nixosModules.minecraft-servers
    inputs.probe-rs-rules.nixosModules.x86_64-linux.default
  ];

  # nixpkgs.overlays = [inputs.nix-minecraft.overlay];

  nixpkgs.config.allowUnfree = true;
  nixpkgs.config.permittedInsecurePackages = [
    "ventoy-1.1.10"
  ];
  # Perform garbage collection weekly to maintain low disk usage

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  # systemd = {
  #   user.services.polkit-gnome-authentication-agent-1 = {
  #     description = "polkit-gnome-authentication-agent-1";
  #     wantedBy = ["graphical-session.target"];
  #     wants = ["graphical-session.target"];
  #     after = ["graphical-session.target"];
  #     serviceConfig = {
  #       Type = "simple";
  #       ExecStart = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
  #       Restart = "on-failure";
  #       RestartSec = 1;
  #       TimeoutStopSec = 10;
  #     };
  #   };
  # };

  boot = {
    binfmt = {
      preferStaticEmulators = true;
      registrations.riscv64 = {
        # We use the static qemu-user binary
        interpreter = "${pkgs.pkgsStatic.qemu-user}/bin/qemu-riscv64";

        # Magic bytes for RISC-V 64-bit
        magicOrExtension = "\\x7fELF\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\xf3\\x00";

        # Mask to ignore insignificant bytes
        mask = "\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff";

        fixBinary = true;

        wrapInterpreterInShell = false;
      };
    };
    loader.systemd-boot = {
      enable = true;
      configurationLimit = 10;
      extraEntries = {
        "lfs.conf" = ''
          title LFS
          linux /EFI/lfs/vmlinuz-6.16.7-lfs-ml-12.4-28-systemd
          options root=PARTUUID=e415e6a5-6756-473d-bed4-ce8d41fbb929 rw
        '';
      };
    };
    loader.efi.canTouchEfiVariables = true;
    kernelParams = [
      "amd_pstate=guided"
      "microcode.amd_sha_check=off"
      "acpi_enforce_resources=lax"
      #       "amd_iommu=on"
      # "iommu=pt"
      # "vfio-pci.ids=1002:73bf"
    ];
    extraModprobeConfig = ''
      options it87 force_id=0x8628 ignore_resource_conflict=1
    '';
    kernel.sysctl = {
      "vm.swappiness" = 10;

      "vm.vfs_cache_pressure" = 50;
    };
  };
  powerManagement.cpuFreqGovernor = "schedutil";
  time.hardwareClockInLocalTime = true;

  virtualisation.docker.enable = true;
  # virtualisation = {
  #   libvirtd = {
  #     enable = true;
  #     qemu.runAsRoot = true;
  #     # qemuOvmf = pkgs.OVMFFull.fd;
  #   };
  #   # qemu = {
  #   #   enable = true;
  #   #   # Allow QEMU to access USB devices, etc.
  #   #   runAsRoot = true;
  #   # };
  #   # Enable UEFI (OVMF) support for the VM
  #   # efi.OVMF = pkgs.OVMF.fd;
  # };

  hardware = {
    graphics.enable = true;
    amdgpu.overdrive.enable = true;
    probe-rs.enable = true;
    # fancontrol = {
    #   enable = true;
    #   config = ''
    #     # Configuration file generated by pwmconfig, changes will be lost
    #     INTERVAL=10
    #     DEVPATH=hwmon1=devices/pci0000:00/0000:00:08.1/0000:12:00.0 hwmon3=devices/platform/it87.2624 hwmon4=devices/pci0000:00/0000:00:18.3 hwmon5=devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/DEADBEEF-2001-0000-00A0-C90629100000
    #     DEVNAME=hwmon1=amdgpu hwmon3=it8628 hwmon4=k10temp hwmon5=gigabyte_wmi
    #     FCTEMPS=hwmon3/pwm1=hwmon4/temp1_input hwmon3/pwm2=hwmon1/temp1_input hwmon3/pwm3=hwmon5/temp3_input
    #     FCFANS=hwmon3/pwm1=hwmon3/fan1_input hwmon3/pwm2=hwmon3/fan2_input hwmon3/pwm3=hwmon3/fan3_input
    #     MINTEMP=hwmon3/pwm1=20 hwmon3/pwm2=20 hwmon3/pwm3=20
    #     MAXTEMP=hwmon3/pwm1=60 hwmon3/pwm2=60 hwmon3/pwm3=60
    #     MINSTART=hwmon3/pwm1=150 hwmon3/pwm2=150 hwmon3/pwm3=150
    #     MINSTOP=hwmon3/pwm1=0 hwmon3/pwm2=0 hwmon3/pwm3=0
    #   '';
    # };
  };

  networking.hostName = "poseidon";
  networking.networkmanager.enable = true;

  time.timeZone = "America/New_York";

  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "Lat2-Terminus16";
    useXkbConfig = true; # use xkb.options in tty.
  };

  services = {
    displayManager = {
      lemurs = {
        enable = true;
        settings = {
          environment_switcher.include_tty_shell = true;
        };
      };
      sessionPackages = [pkgs.sway];
    };
    fstrim.enable = true;
    udev = {
      enable = true;
      extraRules = ''
        # Set 'none' (noop) scheduler for all NVMe devices
        ACTION=="add|change", KERNEL=="nvme[0-9]*n[0-9]*", ATTR{queue/scheduler}="none"

        # Optional: Do the same for any non-rotational SATA devices (SSDs)
        ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="none"

        SUBSYSTEM=="usb", ATTRS{idVendor}=="303a", ATTRS{idProduct}=="1001", MODE="0660", GROUP="dialout", TAG+="uaccess"
      '';
    };
    mysql = {
      enable = true;
      package = pkgs.mariadb;
    };
    printing = {
      enable = true;
      allowFrom = ["all"];
      browsing = true;
      defaultShared = true;
      openFirewall = true;
    };
    pipewire = {
      enable = true;
      pulse.enable = true;
      alsa.enable = true;
    };
    ucodenix = {
      enable = true;
      cpuModelId = "00A60F12";
    };
    avahi = {
      enable = true;
      nssmdns4 = true;
      openFirewall = true;
    };
    openssh = {
      enable = true;
    };
    gnome.gnome-keyring.enable = true;
    # minecraft-servers = {
    #   enable = true;
    #   eula = true;
    #
    #   servers = {
    #     solo_world = let
    #       modpack = pkgs.fetchPackwizModpack {
    #         url = "https://github.com/michaelpennington/server_mods/raw/refs/heads/main/pack.toml";
    #         packHash = "sha256-wTsTRRM8JwOaOyRqE6+uhvnSSFM4NU38iIpbtGK/Ozo=";
    #       };
    #       mcVersion = modpack.manifest.versions.minecraft;
    #       fabricVersion = modpack.manifest.versions.fabric;
    #       serverVersion = lib.replaceStrings ["."] ["_"] "fabric-${mcVersion}";
    #     in {
    #       enable = true;
    #       package = pkgs.fabricServers.${serverVersion}.override {loaderVersion = fabricVersion;};
    #       autoStart = false;
    #       symlinks = {
    #         "mods" = "${modpack}/mods";
    #       };
    #       serverProperties = {
    #         # level-name = "Survival World";
    #         difficulty = "hard";
    #         pause-when-empty-seconds = -1;
    #       };
    #       files = {
    #         "config" = "${modpack}/config";
    #       };
    #       jvmOpts = "-Xms8G -Xmx12G -XX:+UseZGC -XX:+ZGenerational -XX:SoftMaxHeapSize=10g -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+PerfDisableSharedMem -XX:+UseDynamicNumberOfGCThreads";
    #     };
    #   };
    # };
  };

  users = {
    users = {
      mpennington = {
        isNormalUser = true;
        extraGroups = [
          "wheel"
          "networkmanager"
          "dialout"
          "audio"
          "video"
          "libvirtd"
          "seat"
          "input"
          "kvm"
          "adbuser"
          "plugdev"
          "docker"
        ]; # Enable ‘sudo’ for the user.
      };
      lfs = {
        isNormalUser = true;
        extraGroups = [
          "wheel"
          "networkmanager"
          "lfs"
        ];
      };
    };
    groups = {
      plugdev = {
        members = ["mpennington"];
      };
      lfs = {
        name = "lfs";
        members = ["lfs"];
      };
    };
  };

  nix = {
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 1w";
    };
    settings = {
      auto-optimise-store = true;
      trusted-users = [
        "root"
        "mpennington"
      ];
      experimental-features = [
        "nix-command"
        "flakes"
      ];
    };
  };

  environment.systemPackages = with pkgs; [
    inputs.alejandra.defaultPackage.${stdenv.hostPlatform.system}
    inputs.nixd.packages.${stdenv.hostPlatform.system}.default
    lm_sensors
    amdgpu_top
    taplo
    taskwarrior3
    linuxPackages.zenpower
    radeontop
    lz4
    pciutils
    wineWow64Packages.waylandFull
    winetricks
    virt-manager
    virtio-win
    bat
    file
    zip
    nodePackages.js-beautify
    unzip
    xmlstarlet
    bottom
    eza
    fd
    screen
    podman
    gcc
    gh
    # packwiz
    ripgrep
    black
    isort
    rustup
    parallel
    prettier
    gnumake
    usbutils
    stow
    vscode-extensions.vadimcn.vscode-lldb
    w3m
    wget
    xdg-user-dirs
    (
      let
        base = pkgs.appimageTools.defaultFhsEnvArgs;
      in
        pkgs.buildFHSEnv (
          base
          // {
            name = "fhs";
            targetPkgs = pkgs:
            # pkgs.buildFHSUserEnv provides only a minimal FHS environment,
            # lacking many basic packages needed by most software.
            # Therefore, we need to add them manually.
            #
            # pkgs.appimageTools provides basic packages required by most software.
              (base.targetPkgs pkgs)
              ++ (with pkgs; [
                pkg-config
                ncurses
                bison
                python3
                gnumake
                gcc
                texinfo
                m4
                patch
              ]);
            profile = "export FHS=1";
            runScript = "bash";
            extraOutputsToInstall = ["dev"];
          }
        )
    )
  ];

  fonts.packages = with pkgs; [
    fantasque-sans-mono
    fira-code
    fira-code-symbols
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
    nerd-fonts.fantasque-sans-mono
    nerd-fonts.fira-code
  ];

  programs = {
    corectrl = {
      enable = true;
    };
    sway = {
      enable = true;
    };
    steam = {
      enable = true;
      remotePlay.openFirewall = true; # Open ports in the firewall for Steam Remote Play
      dedicatedServer.openFirewall = true; # Open ports in the firewall for Source Dedicated Server
      localNetworkGameTransfers.openFirewall = true; # Open ports in the firewall for Steam Local Network Game Transfers
    };
    nix-ld = {
      enable = true;
      libraries = with pkgs; [
        squashfsTools
        glib
        nss
        cups
        libdrm
        gdk-pixbuf
        gtk3
        pango
        cairo
        libx11
        libxcomposite
        libxdamage
        libxext
        libxfixes
        libxrandr
        libxcb
        libxkbcommon
        alsa-lib
        libgbm
        expat
        nspr
        dbus
        at-spi2-atk
      ];
    };
    fish.enable = true;
    git.enable = true;
    tmux.enable = true;
  };

  xdg.portal = {
    enable = true;

    config = {
      common = {
        default = [
          "gtk"
        ];
        "org.freedesktop.impl.portal.Secret" = [
          "gnome-keyring"
        ];
        extraPortals = with pkgs; [
          xdg-desktop-portal-gtk
        ];
      };
    };
  };

  security.polkit = {
    enable = true;
    extraConfig = ''
        polkit.addRule(function (action, subject) {
        if (
          subject.isInGroup("users") &&
          [
            "org.freedesktop.login1.reboot",
            "org.freedesktop.login1.reboot-multiple-sessions",
            "org.freedesktop.login1.power-off",
            "org.freedesktop.login1.power-off-multiple-sessions",
          ].indexOf(action.id) !== -1
        ) {
          return polkit.Result.YES;
        }
      });
    '';
  };

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "24.05"; # Did you read the comment?
}
